kafka:
  bootstrap_servers:
    - "rpk0.bitquery.io:9092"
    - "rpk1.bitquery.io:9092"
    - "rpk2.bitquery.io:9092"
  security_protocol: "SASL_PLAINTEXT"
  sasl_mechanism: "SCRAM-SHA-512"
  sasl_username: "<your_username>"
  sasl_password: "<your_password>"
  group_id: "<your_username>_token_processor_group"
  auto_offset_reset: "latest"
  enable_auto_commit: false

topic: "eth.tokens.proto"

workers: 10

aws:
  region: "us-east-1"
  ddb_table_name: "ethereum_eth_tx_balances"
